{% set name = "nds2-client" %}
{% set version = "0.16.4" %}
{% set sha256 = "bca6f96583c6710726ea318ac2feb9db3e7e7c9703e019366d1b4ee6f7a4ee87" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - cmake >=3.6
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libcurl
    - krb5  # [win]
    - cyrus-sasl  # [not win]
  run:
    - krb5  # [win]
    - cyrus-sasl  # [not win]

test:
  commands:
    - nds-client-config --includedir --libdir  # [not win]
    - nds_query --version

about:
  home: https://wiki.ligo.org/DASWG/NDSClient
  doc_url: https://nds.docs.ligo.org/nds2-client/Beta/User/html/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: NDS2 Client interface
  description: |
    The NDS2 client interface allows the user to down-load LIGO data
    from V1 and V2 LIGO Network Data Servers.

    This package only provides the low-level C/C++ client and associated
    binaries.  If you want to install the Python bindings, please install
    the python-nds2-client package.

extra:
  recipe-maintainers:
    - duncanmmacleod
