{% set name = "nds2-client" %}
{% set version = "0.16.6" %}
{% set sha256 = "a6d83cc0f96f63ca7e045f3923dc178ad48a4869d61d5e2086d184c7965e5e15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  error_overdepending: true
  error_overlinking: true  # [not win]
  number: 2
  run_exports:
    - {{ pin_subpackage("nds2-client", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [unix]
  host:
    - boost-cpp
    - cyrus-sasl  # [not win]
    - krb5  # [win]
  run:
    - cyrus-sasl  # [not win]
    - krb5  # [win]

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - nds-client-config --includedir --libdir  # [not win]
    - nds_query --version
    - pkg-config --print-errors --modversion nds2-client libndscxx conlibndscxx nds-client-tester  # [unix]

about:
  home: https://wiki.ligo.org/Computing/NDSClient
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: NDS2 Client interface
  description: |
    The NDS2 client interface allows the user to down-load LIGO data
    from V1 and V2 LIGO Network Data Servers.

    This package only provides the low-level C/C++ client and associated
    binaries.  If you want to install the Python bindings, please install
    the python-nds2-client package.

extra:
  recipe-maintainers:
    - duncanmmacleod
