{% set name = "nds2-client" %}
{% set version = "0.16.2" %}
{% set sha256 = "485ce5cc1650f384897e5ddcd259ad2f4f6b63e309372990b997d86b54cf529e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win and vc<14]

requirements:
  build:
    - make
    - cmake >=3.6
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libcurl
    - krb5  # [win]
    - cyrus-sasl  # [not win]
  run:
    - krb5  # [win]
    - cyrus-sasl  # [not win]

test:
  commands:
    - nds-client-config --includedir --libdir  # [not win]
    - nds_query --version

about:
  home: https://wiki.ligo.org/DASWG/NDSClient
  doc_url: https://nds.docs.ligo.org/nds2-client/Beta/User/html/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: NDS2 Client interface
  description: |
    The NDS2 client interface allows the user to down-load LIGO data
    from V1 and V2 LIGO Network Data Servers.

extra:
  recipe-maintainers:
    - duncanmmacleod
