travis:
  secure:
    BINSTAR_TOKEN: X12COE8ewxXu5b49QtuE0I9A4YHckWDJJrYhcUMMr06XJPafu9dPv0b4tj3wxyZcm90N3/zZZMc96/Stg3GohJ4PPlRericif+4PkdLmnMHVBhtb+nNtdgI4soe26fJ8vc6kzWBNOfIEMm/0J4JN6S77B1PaaYRXkXBWsjrCDgCGUtBj3Q9Ug95pdEXbOvwiqLqUYyVO/y1XQbmxvDrVihLlF/ix7JpVdRCORVYAoGNy3SfFszBLjjWqbiN4qlO5zIZolDDMBFcrN3qagJZfOMivj2O6HCth2i/Mlsce5lVel0CCWfEGncYlqvVnWmbSB/uEZS4QWy+67haGiVKae1GgILfOjWSCikzIcA7NfuM238pOMM6IgmQmXxIMMMz5reJNJjqwZna0hePrwOMXmr43GrB7BOBkWJGGoWikp+LmXBoYGWiVtfuoBzosR1+oWjnyUvwGx/v97AR79PQ8Kwo5LkBh8HWZhlro8UZ2CQ4bQHNo/QSKjQrRyapSfpxoYU22kbwAEV3f7R8XHWDQIlHY1k170B/+QiUQ2qISsAD0gXtfJ9UEOtKNBH8kyAXAkUAGlN5ckF6HJTasEEqa2u1Wt3XrMRCb+e5BLhCDG8TQ9VSWeXQtUzGznFhwpOb9ZXxePn8DtGJDs+WAR6O71bUU1Nq4JUulh/OxeXRvero=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
